### ISSUE TITLE
Config is not retained.

### ISSUE THREAD

**Issue by sagarchalise** [flathub/com.viber.Viber#3]
Viber configs are not retained and seems configs are not written into `$HOME/.ViberPC`

If `$HOME/.ViberPC`is not present it needs to be created but seems thats not happening.

This leads to entering phone numbers everytime we run `Viber`.

**Comment by rpallai** [comment]
@TingPing `flatpak update` says i am on the latest version today but I'm still struggling with this. This patch not included in my version? How can I be sure?

**Comment by TingPing** [comment]
@rpallai What is the output of `flatpak info com.viber.Viber`

**Comment by rpallai** [comment]
```
[dap@dh dap]$ flatpak info com.viber.Viber
Ref: app/com.viber.Viber/x86_64/stable
ID: com.viber.Viber
Arch: x86_64
Branch: stable
Origin: flathub
Commit: 31af0cf2ba3f302a55f41298d6b04c126a4a46cab361f113d80f50019f3e56eb
Location: /var/lib/flatpak/app/com.viber.Viber/x86_64/stable/31af0cf2ba3f302a55f41298d6b04c126a4a46cab361f113d80f50019f3e56eb
Installed size: 39.8 MB
Runtime: org.freedesktop.Platform/x86_64/1.6
```

I have ~/.Viber-PC directory but empty.

**Comment by sagarchalise** [comment]
I have ~/.ViberPC with configs uptodate but its not retained. The info part is same as that of 
@rpallai

**Comment by rpallai** [comment]
Some more details: in the namespace of Viber there is a ~/.ViberPC folder with my up-to-date configs but that is not visible outside of the namespace (not retained). On the other hand, there is a ~/.Viber-PC folder visible inside and outside (retained) but that is empty. I think the problem is flatpak expects files in ~/.Viber-PC but Viber uses ~/.ViberPC apparently.

**Comment by rpallai** [comment]
@TingPing Verified, solved. Thanks!
