### ISSUE TITLE
Viber fails to open

### ISSUE THREAD

**Issue by Karam1phill** [flathub/com.viber.Viber#53]
This happened after update. 
I'm running it on ElementaryOS 6.1
Here\s the code:
`flatpak run com.viber.Viber
QIBusPlatformInputContext: invalid portal bus.
Qt: Session management error: None of the authentication protocols specified are supported
QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: Windows, Fusion
sh: line 1: xdg-mime: command not found
qt.webenginecontext: 

GLImplementation: desktop
Surface Type: OpenGL
Surface Profile: NoProfile
Surface Version: 3.1
Using Default SG Backend: yes
Using Software Dynamic GL: no
Using Angle: no

Init Parameters:
  *  allow-loopback-in-peer-connection  
  *  application-name ViberPC 
  *  autoplay-policy no-user-gesture-required 
  *  browser-subprocess-path /app/extra/viber/libexec/QtWebEngineProcess 
  *  disable-features DnsOverHttpsUpgrade,ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture,AudioServiceOutOfProcess 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess,NetworkServiceInProcess 
  *  enable-threaded-compositing  
  *  enable-usermedia-screen-capture  
  *  in-process-gpu  
  *  use-gl desktop 

QQmlApplicationEngine failed to load component
qrc:/Resources/QML/MainWindow.qml: module "adwaita" is not installed
qt.core.qobject.connect: QObject::connect(QWindow, ApplicationEngine): invalid nullptr parameter
`

**Comment by kalligator** [comment]
You need to edit the launcher file `com.viber.Viber.desktop` in `/home/user/.local/share/flatpak/app/com.viber.Viber/x86_64/stable/active/export/share/applications` and prepend the Exec command with `env QT_STYLE_OVERRIDE=""` so it becomes: 
`Exec=env QT_STYLE_OVERRIDE="" /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=viber com.viber.Viber` 

It's best to copy that file into `~/.local/share/applications` so that it doesn't get overwritten.

Ditto if you go the native .deb way, the `viber.desktop` you need to edit/copy is in `/usr/share/applications`.

There are still some bugs though for both packages, at least for me, I don't get any options to open/exit viber when right clicking on it's tray icon and the option to start hidden is grayed out, together with the option to startup on boot but this one was inactive in previous versions as well (though easily solvable).

**Comment by akurtakov** [comment]
Do you still face this one?

**Comment by itoshkov** [comment]
> Do you still face this one?

Yes, I still do. The workaround by @kalligator does the trick.

P.S. I'm on elementary OS 7.

**Comment by hifron** [comment]
`WAYLAND_DISPLAY=wayland-0 QT_QPA_PLATFORM=wayland viber.AppImage`

**Comment by akurtakov** [comment]
There is new version of Viber on latest 23.08 freedesktop runtime. Please update and let us know if it still fails for you?

**Comment by itoshkov** [comment]
> There is new version of Viber on latest 23.08 freedesktop runtime. Please update and let us know if it still fails for you?

It works for me. Thanks!

Here is the version that I have installed:
```bash
$ flatpak list | grep viber
Viber	com.viber.Viber	20.3.0.1	stable	flathub	user
```
